#! /bin/sh
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
VENV_DIR="$SCRIPT_DIR/.assigner-virtualenv"

if [ ! -d "$VENV_DIR" ]; then
	echo "Setting up virtual environment in $VENV_DIR"
	virtualenv --python=python3.5 "$VENV_DIR"
	echo "Installing dependencies"
	# Calling virtualenv's pip directly breaks if there are spaces in the pathname
	# see https://github.com/pypa/pip/issues/923
	"$VENV_DIR/bin/python" "$VENV_DIR/bin/pip" install -r "$SCRIPT_DIR/requirements.txt"
fi

"$VENV_DIR/bin/python" "$SCRIPT_DIR/assigner.py" "$@"
