#! /bin/sh
# Check for -f (BSD coreutils doesn't have it)
readlink -f "$0" &> /dev/null

if [ "$?" != "0" ]; then
  SCRIPT_DIR=$(cd "$(dirname "$0")" ; pwd -P)
else
  SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
fi
VENV_DIR="$SCRIPT_DIR/.assigner-virtualenv"

if [ ! -d "$VENV_DIR" ]; then
	echo "Setting up virtual environment in $VENV_DIR"
	virtualenv --python=python3 "$VENV_DIR"
fi

echo "Installing dependencies"
# Calling virtualenv's pip directly breaks if there are spaces in the pathname
# see https://github.com/pypa/pip/issues/923
"$VENV_DIR/bin/python" "$VENV_DIR/bin/pip" install -r "$SCRIPT_DIR/requirements.txt"

